spring:
  redis:
    host: 192.168.243.128
    port: 6379
    password: jwj422123
    database: 20
    timeout: 10000ms
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

